### ISSUE TITLE
“Hide Free Products” checkbox has no effect

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-connect-woocommerce#11]
Tested by:

1. Giving a product a price of zero:
    <img width="820" alt="edit_product_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/30716979-81515ffa-9f13-11e7-95ae-b40e8bee9ad8.png">

2. Ticking the “Hide Free Products” checkbox:
<img width="341" alt="widgets_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/30716963-74932b36-9f13-11e7-9f24-b08331b07540.png">

**Expected**: products with a price of 0 are not visible.

**Actual**: free product is still visible.

<img width="245" alt="test" src="https://user-images.githubusercontent.com/647669/30717071-b6aee136-9f13-11e7-8430-55b730e1d863.png">

**Comment by carasmo** [comment]
Is there an ETA on this fab widget? Thanks!

**Comment by nickcernis** [comment]
@carasmo Should be in the next release, but no timeline for that yet. Thanks for your interest, though!

**Comment by carasmo** [comment]
Thanks!

**Comment by nickcernis** [comment]
This should now be fixed. To test in the develop branch:

## Setup
1. Activate Genessis Sample.
2. Add theme support for the Genesis Featured Product widget with `add_theme_support( 'gencwooc-featured-products-widget' );` in `functions.php`.
3. Add the Genesis Featured Product widget to any widget area.
4. Tick the “hide free products” box in the widget settings..
5. Create a product with a price of sale price of '0', '0.00', or '0,00'.
6. View the widget on the front end.

## Confirmation
- [ ] Products with a price of '0', '0.00', or '0,00' do not appear in the widget.
- [ ] Products with a positive price and a sale price of '0', '0.00', or '0,00' do not appear in the widget.
- [ ] Products with an empty price and sale price still appear (these are not considered 'free').

**Comment by swa433** [comment]
@nickcernis Confirmed +1

- [ ] Products with a price of '0', '0.00', or '0,00' do not appear in the widget.
- [ ] Products with a positive price and a sale price of '0', '0.00', or '0,00' do not appear in the widget.
- [x] Products with an empty price and sale price still appear (these are not considered 'free').
- [x] Products with a non-zero price and non-zero sale price still appear.

**Notes:**

The case of "0,00" no longer seems to be applicable, as WooCommerce doesn't seem to allow saving "," or any other thousand seperator in sale or regular price fields.

Any special characeter other than decimal "." is stripped with a warning
( screenshot: http://nimb.ws/3Op4M5 )

As a result "0,00" in sale or regular price field becomes "000", which is not covered in the array, used in the plugin's comparisn code:

`'value'   => array('0', '0.00', '0,00'),`

We can either drop the check for the value "0,00" or add some additional array values in that array e.g. "000", "0000", "00000" etc

**Environment:**
WordPress:
Version: 4.9.7

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Genesis Sample (active theme):
Version: 2.6.0

WooCommerce:
Version: 3.4.3

**Comment by nickcernis** [comment]
Thanks for looking at this, @swa433!

> The case of "0,00" no longer seems to be applicable, as WooCommerce doesn't seem to allow saving "," or any other thousand seperator in sale or regular price fields.

I'm able to set price to `0,00` if I swap the default thousand and decimal separator (so that decimal is `,`) at WooCommerce → Settings → General:

<img width="843" alt="woocommerce_settings_ _test_site_ _wordpress" src="https://user-images.githubusercontent.com/647669/42535133-e599ee76-848e-11e8-9f73-d588112dc838.png">

From what I can see dots and commas are the two separators in common usage, so I don't think we need to account for other separators: http://www.statisticalconsultants.co.nz/blog/how-the-world-separates-its-decimals.html.

**Comment by nickcernis** [comment]
I've also made an update to cover '00', '000', and '0000' cases too — thanks for spotting that, @swa433.

**Comment by nickcernis** [comment]
Thanks so much for you help with this, @swa433!
